blockscout:
  indexer:
    db:
      proxy:
        resources:
          requests:
            memory: 4Gi
            cpu: 2
    pool_size: 100
    resources:
      requests:
        memory: 12Gi
        cpu: 5
    metrics:
      enabled: true
  api:
    autoscaling:
      maxReplicas: 2
      minReplicas: 1
      target:
        cpu: 70
    db:
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 700m
    pool_size: 10
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
  web:
    host: blockscoutstagingrc1-blockscout3.celo-testnet.org
    autoscaling:
      maxReplicas: 2
      minReplicas: 1
      target:
        cpu: 70
    db:
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 700m
    pool_size: 10
    resources:
      requests:
        memory: 250M
        cpu: 500m
    recaptchaSecretName: blockscoutstagingrc1-blockscout-recaptcha
  metadata_crawler:
    enabled: true
  archiveNodes:
    jsonrpc_http_url: http://mainnet-archive-service.blockscoutstagingrc1.svc.cluster.local:8545
    jsonrpc_ws_url: ws://mainnet-archive-service.blockscoutstagingrc1.svc.cluster.local:8545
  metrics:
    enabled: false
  chain:
    subnetwork: Celo
    networkID: 42220
