apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-rbac
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-rbac
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
    iam.gke.io/gcp-service-account: {{ .Release.Name }}-rbac@{{ .Values.blockscout.projectId }}.iam.gserviceaccount.com
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
