{{- if .Values.blockscout.metadataCrawler.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-metadata-crawler
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-metadata-crawler
spec:
  schedule: "{{ .Values.blockscout.metadataCrawler.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "celo.blockscout.labels" . | nindent 12 }}
        spec:
          containers:
          - name: metadata-crawler
            image: {{ .Values.blockscout.metadataCrawler.image.repository }}:{{ .Values.blockscout.metadataCrawler.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            args:
            - -c
            - |
              trap "touch /tmp/pod/main-terminated" EXIT
              node lib/crawler.js
            env:
            - name: LOG_FORMAT
              value: stackdriver
            - name: PGHOST
              value: "127.0.0.1"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "blockscout"
            - name: PROVIDER_URL
              value: {{ .Values.blockscout.archiveNodes.jsonrpcHttpUrl }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: DATABASE_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: DATABASE_PASSWORD
            - name: DISCORD_WEBHOOK_URL
              value: {{ .Values.blockscout.metadataCrawler.discordWebhookUrl }}
            - name: CLUSTER_NAME
              value: {{ .Values.blockscout.metadataCrawler.discordClusterName }}
            volumeMounts:
            - mountPath: /tmp/pod
              name: tmp-pod
{{- $data := dict "Values" .Values "Database" .Values.blockscout.indexer.db }}
{{ include "celo.blockscout-db-terminating-sidecar" $data | indent 10 }}
          restartPolicy: Never
{{- end}}
