{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-api-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /admin/.* {
        deny all;
      }
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}-api.{{ .Values.blockscout.domainName }}
    secretName: {{ .Release.Name }}-api-tls
  rules:
  - host: {{ .Release.Name }}-api.{{ .Values.blockscout.domainName }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-api
            port:
              number: 4000
