apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-migration
spec:
  template:
    metadata:
      labels:
        {{- include "celo.blockscout.labels" . | nindent 8 }}
    spec:
      containers:
      - name: blockscout-migration
        image: {{ .Values.blockscout.image.repository }}:{{ .Values.blockscout.image.tag }}
        imagePullPolicy: {{ .Values.blockscout.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        args:
        - |
           trap "touch /tmp/pod/main-terminated" EXIT
           [ ${DROP_DB} == "true" ] && mix do ecto.drop, ecto.create
           mix do ecto.migrate
        resources:
          requests:
            memory: 250M
            cpu: 200m
        volumeMounts:
          - mountPath: /tmp/pod
            name: temporary-dir
        env:
        - name: DROP_DB
          value: "{{ default "false" .Values.blockscout.db.drop }}"
{{- $data := dict "Release" .Release "Values" .Values "Database" .Values.blockscout.indexer.db }}
{{ include "celo.blockscout.env-vars" $data  | indent 8 }}
{{ include "celo.blockscout.container.db-terminating-sidecar" $data | indent 6 }}
      volumes:
{{ include "celo.blockscout.volume.cloudsql-credentials" . | indent 8 }}
{{ include "celo.blockscout.volume.temporary-dir" . | indent 8 }}
      restartPolicy: Never
  backoffLimit: 0
